### ISSUE TITLE
More Placeholders pls [Just posting this here so its in ya tracker]

### ISSUE THREAD

**Issue by KhaozFrost** [happyzleaf/PixelmonPlaceholders#14]
_team_#_shiny% returns: true/false
&& [Javascript Placeholder for the one above where true = '&6' false = '&3']

modifications to nature to add these
http://prntscr.com/jwdudb nature &7(&a+<> &7: &c-<>&7) chance <> to their positive and negative and nature still nature

modified _ball% or new one like _ballID% to return: poke_ball master_ball etc for uses with:
      ItemType = "pixelmon:%_team_1_ballID" (i know thats technically wrong but just example.

If possible add support for %trainer_team_#_texturelocation% to also return shiny texture if pokemon is shiny and egg texture if pokemon is an egg. and correctly do the pokemon that have different forms

%trainer_team_#_form% (prob needs a way to display all different forms poke can have aswell

_ivtotal%

**Priority Ones Needed to complete Pokebuilder:**

If possible add support for %trainer_team_#_texturelocation% to also return shiny texture if pokemon is shiny and egg texture if pokemon is an egg. and correctly do the pokemon that have different forms

_team_#_shiny% returns: true/false
_hiddenpower%
_evtotal%
_nickname%

**Comment by hqppyz** [comment]
@KhaozFrost can we close this with #15?

**Comment by KhaozFrost** [comment]
yeah it can be closed. 

theres only 1 issue in there with the texture one and thats pyroars female/male sprite
