### ISSUE TITLE
Variable %trainer_balance% is broken

### ISSUE THREAD

**Issue by Malachiel87** [happyzleaf/PixelmonPlaceholders#17]
Hi, i juyst moved from pixelmon gen to pixelmon forged, and the %trainer_balance% placeholder on tab keep showing 0. 
PixelPlaceholder 1.3.1fix
Using Pixelmon Reforged 6.3.4.
Forge 2705
SPongeforge 3361
PixelmonEconomyBridge-1.12.2-2.0.1 (Reforged use a new version of this plugin, maybe it break the mod?)
Totaleconomy 1.8.1
I see also this error on startup https://gist.github.com/xion87/02a8c1d49ceffe92558f7e4ad1014409
The other variables are working fine

**Comment by hqppyz** [comment]
Works fine now, there are some bugs but it's related to latest pixelmon and it's being fixed
