### ISSUE TITLE
Missing Placeholders/

### ISSUE THREAD

**Issue by KhaozFrost** [happyzleaf/PixelmonPlaceholders#18]
OT - Original Trainer
IVS Current / IVS Total
EVS Current / EVS Total

http://prntscr.com/mon2oj

Also might be nice to add the + and minus stuff to the nature one like shown in the screenshot

**Comment by hqppyz** [comment]
I've added `[pokemon]_originaltrainer%`, while we already had `[pokemon]_stats_ivs_total%` and `[pokemon]_stats_evs_total%`.

I forgot to reference and close this in the latest commit tho.
