### ISSUE TITLE
0 Balance when using %trainer_balance%

### ISSUE THREAD

**Issue by Feutor** [happyzleaf/PixelmonPlaceholders#19]
So I just saw that someone else already made this kidna thread but it was closed so yeah, p sure its back:
![grafik](https://user-images.githubusercontent.com/21291598/53368810-070a7600-394a-11e9-8a4d-0a982a409c91.png)

**Comment by hqppyz** [comment]
This is not a bug with Pixelmon Placeholders, it's a problem that has already been reported to the Pixelmon tracker.
