### ISSUE TITLE
This plugin is compatible with virtual chest?

### ISSUE THREAD

**Issue by ClarkHalf** [happyzleaf/PixelmonPlaceholders#20]

**Comment by KhaozFrost** [comment]
yes it is. as long as you are using this version of placeholderapi too
https://github.com/randombyte-developer/PlaceholderAPI/releases

**Comment by ClarkHalf** [comment]
What's wrong

	Slot29 = [{
    Item {
      ItemType = "pixelmon:pixelmon_sprite"
      Count = 1
      UnsafeDamage = 0
      UnsafeData {
        SpriteName = "%party_1_texturelocation%"
      }
      DisplayName = "&5&lLendarios"
      ItemLore = [
                "&7  ►&3 Compre aqui todos os Lendarios do servidor com &6Cash"
                "&7  ►&a Clique aqui para acessar!"
      ]
    }
        KeepOpen = true
        PrimaryAction {
            Command = "vc open decoração"
        }
        IgnoredPermissions = [
            "virtualchest.open.self.decoração"
            ]
        Requirements = "player.hasPermission('virtualchest.open.self.loja')"
    }]

**Comment by ClarkHalf** [comment]
@KhaozFrost

**Comment by KhaozFrost** [comment]
I'm not going to diagnose the vc menu for you. If you have an error log then I can look at that, Also don't need to tag me; I get a email on your responses so its redundant.

**Comment by zsn741656478** [comment]
> What's wrong
> 
> ```
> Slot29 = [{
> Item {
>   ItemType = "pixelmon:pixelmon_sprite"
>   Count = 1
>   UnsafeDamage = 0
>   UnsafeData {
>     SpriteName = "%party_1_texturelocation%"
>   }
>   DisplayName = "&5&lLendarios"
>   ItemLore = [
>             "&7  ►&3 Compre aqui todos os Lendarios do servidor com &6Cash"
>             "&7  ►&a Clique aqui para acessar!"
>   ]
> }
>     KeepOpen = true
>     PrimaryAction {
>         Command = "vc open decoração"
>     }
>     IgnoredPermissions = [
>         "virtualchest.open.self.decoração"
>         ]
>     Requirements = "player.hasPermission('virtualchest.open.self.loja')"
> }]
> ```

You should write like this
      UnsafeData = {
        SpriteName = "pixelmon:sprites/pokemon/1"
      }

**Comment by hqppyz** [comment]
Nope he's good, %party_1_texturelocation% is indeed the placeholder that has to be used there. However, this is not the place to ask for such problems, contact me on discord (happyzlife#6345), I'll sort you there
