### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Malachiel87** [happyzleaf/PixelmonPlaceholders#24]
Using latest Pixelmon reforged 7.0.3 i got this error at startup:
https://gist.github.com/xion87/b6f0334571c8876e1a7532a4d0480610

**Comment by hqppyz** [comment]
Please test it with the latest version of reforged (7.0.4) and the latest version of pixplaceholders (2.1.1) and let me know if anything changes

**Comment by Malachiel87** [comment]
The error is still here
https://gist.github.com/xion87/184b728b4e5754cee321426e167dcd2f

**Comment by hqppyz** [comment]
I need your forge version, your sponge version, and whatever else might be relevant.
Just to make sure that when I can get to test this I have all the info needed.

**Comment by Malachiel87** [comment]
pixelmonplaceholders-2.1.1
PlaceholderAPI-4.5.1
spongeforge-1.12.2-2768-7.1.6-RC3616
Forge 1.12.2 2768
Pixelmon-1.12.2-7.0.5

**Comment by hqppyz** [comment]
Test it with the newest version and feel free to reopen this thread if it's still not working.
