### ISSUE TITLE
More player placeholders

### ISSUE THREAD

**Issue by SnowBlitzz** [happyzleaf/PixelmonPlaceholders#25]
Is it possible to add more placeholders for player stat tracking? Since we already have dexcount, seen count, wins and losses, how about a more specific set for total pokemon defeated, bosses defeated, shinies caught, legendaries caught, etc.

**Comment by hqppyz** [comment]
This would need a tracker, which is far beyond what this plugin's for. I have a private plugin that does that, if enough people want it I can rewrite it and release it, but right now it's under a server's copyright.
