### ISSUE TITLE
Update for reforged 7.0.7

### ISSUE THREAD

**Issue by Malachiel87** [happyzleaf/PixelmonPlaceholders#28]
the plugin need to be updated for use the pokedex counter placeholder...

**Comment by hqppyz** [comment]
I’m really confused about what you’re asking to be fixed. What do you mean by that? Does it not work at all in 7.0.7? Or is it displaying wrong info? Which placeholders?

**Comment by KhaozFrost** [comment]
believe they are referring to this
https://gist.github.com/KhaozFrost/ea837778a361191f43e6dd1b0ac03f11

**Comment by hqppyz** [comment]
Thanks @KhaozFrost mah man always on the spot 🤩
