### ISSUE TITLE
%trainer_wlratio% incorrect

### ISSUE THREAD

**Issue by Shmeeb** [happyzleaf/PixelmonPlaceholders#29]
https://gyazo.com/61fe8f653ae245d35f311136674f6eab

I could me mistaken but shouldn't `%trainer_wlratio%` equal `%trainer_wins%` divided by `%trainer_losses%`, which is 2.15?

UltimateChat config setting:
```
"&eWins:&a %trainer_wins%  &eLosses:&a %trainer_losses%  &eRatio:&a %trainer_wlratio%",
```

Running:
```
pixelmonplaceholders-2.1.3.jar
PlaceholderAPI-4.5.1.jar
spongeforge-1.12.2-2768-7.1.6-RC3616.jar
Pixelmon-1.12.2-7.0.7-universal.jar
```

**Comment by hqppyz** [comment]
Yeah, makes sense. Right now the ratio is calculated by ‘wins / (wins + losses)’ while it should be ‘wins / losses’.
I’m not sure why I did it like that, maybe it was how someone asked me or I just screwed it entirely.
Either way, I’ll fix it in the next release, thanks for the heads up.
