### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by MrBringBacon** [happyzleaf/PixelmonPlaceholders#31]
Just wondering why this issue is happening.
[OneControlCenter] [06:20:43] [Server thread/INFO] [tabmanager]: placeholder service null?

**Comment by KhaozFrost** [comment]
You're going to need to provide more then just that.. upload your latest.log

**Comment by MrBringBacon** [comment]
My bad, here you go.
https://pastebin.com/kMbqdLVV

**Comment by MrBringBacon** [comment]
Hello... wondering if there's any update or fix you can provide me for this issue I'm having...
Here's the config...
https://pastebin.com/gQBZPsaS
Here's it not working in game..
https://imgur.com/a/1xBw6oX

**Comment by MrBringBacon** [comment]
TabManager-2.1.3-S7.0-MC1.12.2.jar
pixelmonplaceholders-2.1.3.jar

**Comment by Proxying** [comment]
PlaceHolderAPI failed to start up correctly due to your files. https://pastebin.com/psK0yfp9

**Comment by KhaozFrost** [comment]
also might be ideal to be using randombytes PR of placeholderapi if you're not already using it.
https://github.com/randombyte-developer/PlaceholderAPI/releases/tag/v4.5.1

**Comment by hqppyz** [comment]
Closing since unrelated
