### ISSUE TITLE
not collect display

### ISSUE THREAD

**Issue by comdarksider** [happyzleaf/PixelmonPlaceholders#34]
I use pixelmon generation 2.9.2 and pixelmonplaceholder 2.1.3

Tab manager 2.1.3 config:
<a href="https://imgur.com/ttqKvPL"><img src="https://i.imgur.com/ttqKvPL.jpg" title="source: imgur.com" /></a>

In game:
<a href="https://imgur.com/JaGSrF9"><img src="https://i.imgur.com/JaGSrF9.jpg?1" title="source: imgur.com" /></a>

How to fix this problem.

**Comment by hqppyz** [comment]
Pixelmon Generations is not supported. The code is public, if you want you can go ahead and try to make a fork for that version, or find someone that's willing to do it.
