### ISSUE TITLE
How to display placeholders in Chinese

### ISSUE THREAD

**Issue by qq2415786013** [happyzleaf/PixelmonPlaceholders#36]
How to display placeholders in Chinese

**Comment by hqppyz** [comment]
To be honest I'm not sure if I should continue to implement features in this badly-programmed shitton of lines.
I'll let you know if I'll do it now or after the rewrite.

**Comment by hqppyz** [comment]
I just remembered that most of the localizable name are indeed localized tho...
I closed the issue #21 which was about the same problem.
