### ISSUE TITLE
Get an error when trying to use API in rankupper

### ISSUE THREAD

**Issue by MaknaeSleek** [happyzleaf/PixelmonPlaceholders#38]
In RankUpper I place the API "%trainer_dexcount%"=10, but when I use it in game it tells me there is an error and the string index is out of range with -1. What do I do to remove this issue?

**Comment by hqppyz** [comment]
I need the actual log.

**Comment by hqppyz** [comment]
The trainer_dexcount placeholder works, so the issue must be about how you're using it with rankup. That statement most likely is wrong. I'm closing this as it's not an issue with pixpapi itself.
