### ISSUE TITLE
Evolution requirement placeholders not working

### ISSUE THREAD

**Issue by Caaethil** [happyzleaf/PixelmonPlaceholders#39]
It seems like placeholders relating to evolution requirements aren't being recognised (though I haven't tested them all). Examples include `<prefix>_evolution_level_level%` and `<prefix>_evolution_move%`. Other placeholders work fine for me. Using PAPI-4.5.1 and PixelmonPlaceholders-2.1.6.

**Comment by hqppyz** [comment]
Sorry buddy
