### ISSUE TITLE
REQUEST: Trainer Dex percentage placeholder changes

### ISSUE THREAD

**Issue by BrandHyde** [happyzleaf/PixelmonPlaceholders#40]
Hi there, currently the trainder dex percentage placeholders show like this (14.54%)

I would really love this plugin to just show the first two numbers, with no decimal point, thank you.

I'm willing to pay for this update

**Comment by BrandHyde** [comment]
Also another note

When having this %trainer_dexpercentage% it shows no percentage.

But this %trainer_dexpercentage%% shows two %%'s after the number? Very confusing not sure how to get around that

**Comment by hqppyz** [comment]
Hello Brandon, may you hit me up on discord? We can continue this there.
happyz#6345
