### ISSUE TITLE
Pixelmon sprite

### ISSUE THREAD

**Issue by Kiriao** [happyzleaf/PixelmonPlaceholders#41]
Hi is it possible to show pokemon sprite using this placeholder?

**Comment by hqppyz** [comment]
Yes, and next time please check the [wiki](https://github.com/happyzleaf/PixelmonPlaceholders/wiki/Placeholders) before asking.
e.g. `%party_1_texturelocation%`

**Comment by Kiriao** [comment]
i know but i mean is to show the spirte as a texture

**Comment by hqppyz** [comment]
That's the value that contains the texture location needed in the nbt of the photo. Where and how to use it depends on the context.
