### ISSUE TITLE
%pokedex_1_biomes% not working

### ISSUE THREAD

**Issue by Kiriao** [happyzleaf/PixelmonPlaceholders#42]
I just found out that %pokedex_1_biomes% is not working as it should
![image](https://user-images.githubusercontent.com/48480973/112967724-235aeb80-917e-11eb-9271-c0985dd8b98a.png)

did i do it wrongly 
![image](https://user-images.githubusercontent.com/48480973/112967843-44bbd780-917e-11eb-9b33-16686212bcff.png)

**Comment by Kiriao** [comment]
And i try using %pokedex_1__postevolutions%, %pokedex_1__preevolutions% and even %pokedex_1__evolutions% it not working as it should i just give me blank at the lore

**Comment by Kiriao** [comment]
> And i try using %pokedex_1__postevolutions%, %pokedex_1__preevolutions% and even %pokedex_1__evolutions% it not working as it should i just give me blank at the lore

Sorry please ignore this comment i miss place the tag

**Comment by Kiriao** [comment]
> I just found out that %pokedex_1_biomes% is not working as it should
> ![image](https://user-images.githubusercontent.com/48480973/112967724-235aeb80-917e-11eb-9271-c0985dd8b98a.png)
> 
> did i do it wrongly
> ![image](https://user-images.githubusercontent.com/48480973/112967843-44bbd780-917e-11eb-9b33-16686212bcff.png)

Did i do the syntax wrongly?

**Comment by hqppyz** [comment]
I'm sorry I'm not very much active, but post the log of the console when you run the command, if it doesn't show up then use your mouse to hover to the red part  `_1_moves%`.

**Comment by Kiriao** [comment]
> I'm sorry I'm not very much active, but post the log of the console when you run the command, if it doesn't show up then use your mouse to hover to the red part `_1_moves%`.

Sorry I think you are mistaken my is not move it biome

**Comment by hqppyz** [comment]
Likewise, do the same for your placeholder please.

**Comment by Kiriao** [comment]
![image](https://user-images.githubusercontent.com/48480973/116065428-92fac280-a6b9-11eb-9988-c67f4bfa9aea.png)

Hi you mean this?? it say disable how come?

**Comment by hqppyz** [comment]
Sorry buddy
