### ISSUE TITLE
Not all moves showing up for %party_1_moves%

### ISSUE THREAD

**Issue by mrneezee** [happyzleaf/PixelmonPlaceholders#44]
![2021-04-21_10 56 23](https://user-images.githubusercontent.com/13089835/115592583-a0b2e100-a290-11eb-8a98-fd725ce8cc6f.png)
![2021-04-21_10 56 58](https://user-images.githubusercontent.com/13089835/115592587-a27ca480-a290-11eb-8842-60b92bc7859f.png)
in the chat you can see that surf doesn't show up in the place holder %party_1_moves% but Blastoise can learn surf through a TR
I used th command /papi parse (name) %party_1_moves%

**Comment by hqppyz** [comment]
I'm sure the code only referred to learnable moves or something like that. Must've forgot to add all other attacks.
Anyway, bye bye (project is dead)
