### ISSUE TITLE
Request: (If Possible) Wait for PlaceholderAPI check-up

### ISSUE THREAD

**Issue by MysticalSquirrel** [happyzleaf/PixelmonPlaceholders#45]
Could it be possible to add some sort of check-up or 'wait-for' method to ensure that PlaceholderAPI loads before PixelmonPlaceholders?

I just had a small issue when trying to load the API into a SpongeForge server and after discussing with someone from the Sponge forums managed to get the server to work by re-ordering the mods/plugins in the folder.

I don't know if the PixelmonPlaceholders is used for both Reforged and Gens, but I thought it would be useful for both.

**Comment by hqppyz** [comment]
Well, I'm sure no one needs this anymore but for the sake of it, this plugin was already named with a 'z' as the first character to prevent this kind of problems. So this makes no sense to me.
