### ISSUE TITLE
Sugestion of + PlaceHolders

### ISSUE THREAD

**Issue by EverNife** [happyzleaf/PixelmonPlaceholders#5]
A few more placeholders would be really cool!

```
%<prefix>  _shiny% returning "true" or "false"
%<prefix>  _growth% returing growth, (exemple, "Huge", etc)
```

**Comment by hqppyz** [comment]
Will add with the next update probably

**Comment by Lorrainrm** [comment]
Perhaps a _allmoves% / _allmoves_1% / 2, 3, 4...
Would be usefull for a custom menu where a player could pick the moves, for example.

**Comment by hqppyz** [comment]
Closing, now wait for 1.4.0, it's coming out in some days!
@Lorrainrm you might want to open another issue, but please explain better.
