### ISSUE TITLE
Variable max party slot not used in error message on line 85.

### ISSUE THREAD

**Issue by HollowMisty** [happyzleaf/PixelmonPlaceholders#51]
PixelmonPlaceholders/src/main/java/com/github/happyzleaf/pixelmonplaceholders/Placeholders.java

line 85:
			throw new NoValueException("Missing party slot. [1-6]");			

line 95:		
			throw new NoValueException(String.format("The party slot must be between 1 and %d.", PlayerPartyStorage.MAX_PARTY));

**Comment by hqppyz** [comment]
This means nothing to me.
Feel free to reopen this with more info, but please note that this plugin is outdated, people now use other alternatives.
