### ISSUE TITLE
Issue when players join. Pixelmon reforged 6.2.2

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [happyzleaf/PixelmonPlaceholders#6]
https://gyazo.com/8f7624c82f64e46adc9b6bb328fd1b5e
[nucleus-info-20180313-153804.txt](https://github.com/happyzleaf/PixelmonPlaceholders/files/1808403/nucleus-info-20180313-153804.txt)

**Comment by hqppyz** [comment]
@KyleCG8094 this is a very random crash, i have no clue what could have caused that. If that shows out again please add the full log, and everything that could help me understanding what's wrong.
I will keep this issue open

**Comment by hqppyz** [comment]
Cannot be reproduced. Closing until more information comes out.
